# CMake generated Testfile for 
# Source directory: D:/workspace_github/openMVG/src/openMVG/multiview
# Build directory: D:/workspace_github/openMVG/bin64/openMVG/multiview
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_test_triangulation "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_test_triangulation.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_test_triangulation "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_test_triangulation.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_test_triangulation "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_test_triangulation.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_test_triangulation "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_test_triangulation.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_test_triangulation "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_test_triangulation.exe")
else()
  add_test(openMVG_test_triangulation NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_test_triangulation_nview "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_test_triangulation_nview.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_test_triangulation_nview "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_test_triangulation_nview.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_test_triangulation_nview "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_test_triangulation_nview.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_test_triangulation_nview "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_test_triangulation_nview.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_test_triangulation_nview "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_test_triangulation_nview.exe")
else()
  add_test(openMVG_test_triangulation_nview NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_test_solver_affine "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_test_solver_affine.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_test_solver_affine "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_test_solver_affine.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_test_solver_affine "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_test_solver_affine.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_test_solver_affine "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_test_solver_affine.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_test_solver_affine "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_test_solver_affine.exe")
else()
  add_test(openMVG_test_solver_affine NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_test_solver_fundamental_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_test_solver_fundamental_kernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_test_solver_fundamental_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_test_solver_fundamental_kernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_test_solver_fundamental_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_test_solver_fundamental_kernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_test_solver_fundamental_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_test_solver_fundamental_kernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_test_solver_fundamental_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_test_solver_fundamental_kernel.exe")
else()
  add_test(openMVG_test_solver_fundamental_kernel NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_test_solver_essential_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_test_solver_essential_kernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_test_solver_essential_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_test_solver_essential_kernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_test_solver_essential_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_test_solver_essential_kernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_test_solver_essential_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_test_solver_essential_kernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_test_solver_essential_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_test_solver_essential_kernel.exe")
else()
  add_test(openMVG_test_solver_essential_kernel NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_test_solver_homography_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_test_solver_homography_kernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_test_solver_homography_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_test_solver_homography_kernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_test_solver_homography_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_test_solver_homography_kernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_test_solver_homography_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_test_solver_homography_kernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_test_solver_homography_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_test_solver_homography_kernel.exe")
else()
  add_test(openMVG_test_solver_homography_kernel NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_test_solver_essential_five_point "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_test_solver_essential_five_point.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_test_solver_essential_five_point "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_test_solver_essential_five_point.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_test_solver_essential_five_point "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_test_solver_essential_five_point.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_test_solver_essential_five_point "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_test_solver_essential_five_point.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_test_solver_essential_five_point "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_test_solver_essential_five_point.exe")
else()
  add_test(openMVG_test_solver_essential_five_point NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_test_solver_resection_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_test_solver_resection_kernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_test_solver_resection_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_test_solver_resection_kernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_test_solver_resection_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_test_solver_resection_kernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_test_solver_resection_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_test_solver_resection_kernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_test_solver_resection_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_test_solver_resection_kernel.exe")
else()
  add_test(openMVG_test_solver_resection_kernel NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_test_solver_translation_knownRotation_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_test_solver_translation_knownRotation_kernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_test_solver_translation_knownRotation_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_test_solver_translation_knownRotation_kernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_test_solver_translation_knownRotation_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_test_solver_translation_knownRotation_kernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_test_solver_translation_knownRotation_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_test_solver_translation_knownRotation_kernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_test_solver_translation_knownRotation_kernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_test_solver_translation_knownRotation_kernel.exe")
else()
  add_test(openMVG_test_solver_translation_knownRotation_kernel NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_test_rotation_averaging "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_test_rotation_averaging.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_test_rotation_averaging "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_test_rotation_averaging.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_test_rotation_averaging "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_test_rotation_averaging.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_test_rotation_averaging "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_test_rotation_averaging.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_test_rotation_averaging "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_test_rotation_averaging.exe")
else()
  add_test(openMVG_test_rotation_averaging NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_test_translation_averaging "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_test_translation_averaging.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_test_translation_averaging "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_test_translation_averaging.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_test_translation_averaging "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_test_translation_averaging.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_test_translation_averaging "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_test_translation_averaging.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_test_translation_averaging "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_test_translation_averaging.exe")
else()
  add_test(openMVG_test_translation_averaging NOT_AVAILABLE)
endif()
