# CMake generated Testfile for 
# Source directory: D:/workspace_github/openMVG/src/openMVG/linearProgramming/lInfinityCV
# Build directory: D:/workspace_github/openMVG/bin64/openMVG/linearProgramming/lInfinityCV
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_lInftyCV_test_triangulation "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_lInftyCV_test_triangulation.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_lInftyCV_test_triangulation "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_lInftyCV_test_triangulation.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_lInftyCV_test_triangulation "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_lInftyCV_test_triangulation.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_lInftyCV_test_triangulation "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_lInftyCV_test_triangulation.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_lInftyCV_test_triangulation "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_lInftyCV_test_triangulation.exe")
else()
  add_test(openMVG_lInftyCV_test_triangulation NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_lInftyCV_test_resection "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_lInftyCV_test_resection.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_lInftyCV_test_resection "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_lInftyCV_test_resection.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_lInftyCV_test_resection "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_lInftyCV_test_resection.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_lInftyCV_test_resection "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_lInftyCV_test_resection.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_lInftyCV_test_resection "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_lInftyCV_test_resection.exe")
else()
  add_test(openMVG_lInftyCV_test_resection NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_lInftyCV_test_resection_robust "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_lInftyCV_test_resection_robust.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_lInftyCV_test_resection_robust "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_lInftyCV_test_resection_robust.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_lInftyCV_test_resection_robust "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_lInftyCV_test_resection_robust.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_lInftyCV_test_resection_robust "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_lInftyCV_test_resection_robust.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_lInftyCV_test_resection_robust "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_lInftyCV_test_resection_robust.exe")
else()
  add_test(openMVG_lInftyCV_test_resection_robust NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_lInftyCV_test_global_translations_fromTriplets "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_lInftyCV_test_global_translations_fromTriplets.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_lInftyCV_test_global_translations_fromTriplets "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_lInftyCV_test_global_translations_fromTriplets.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_lInftyCV_test_global_translations_fromTriplets "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_lInftyCV_test_global_translations_fromTriplets.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_lInftyCV_test_global_translations_fromTriplets "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_lInftyCV_test_global_translations_fromTriplets.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_lInftyCV_test_global_translations_fromTriplets "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_lInftyCV_test_global_translations_fromTriplets.exe")
else()
  add_test(openMVG_lInftyCV_test_global_translations_fromTriplets NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_lInftyCV_test_global_translations_fromTij "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_lInftyCV_test_global_translations_fromTij.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_lInftyCV_test_global_translations_fromTij "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_lInftyCV_test_global_translations_fromTij.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_lInftyCV_test_global_translations_fromTij "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_lInftyCV_test_global_translations_fromTij.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_lInftyCV_test_global_translations_fromTij "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_lInftyCV_test_global_translations_fromTij.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_lInftyCV_test_global_translations_fromTij "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_lInftyCV_test_global_translations_fromTij.exe")
else()
  add_test(openMVG_lInftyCV_test_global_translations_fromTij NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_lInftyCV_test_tijsAndXis "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_lInftyCV_test_tijsAndXis.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_lInftyCV_test_tijsAndXis "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_lInftyCV_test_tijsAndXis.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_lInftyCV_test_tijsAndXis "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_lInftyCV_test_tijsAndXis.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_lInftyCV_test_tijsAndXis "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_lInftyCV_test_tijsAndXis.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_lInftyCV_test_tijsAndXis "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_lInftyCV_test_tijsAndXis.exe")
else()
  add_test(openMVG_lInftyCV_test_tijsAndXis NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_lInftyCV_test_tijsAndXis_outlier "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_lInftyCV_test_tijsAndXis_outlier.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_lInftyCV_test_tijsAndXis_outlier "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_lInftyCV_test_tijsAndXis_outlier.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_lInftyCV_test_tijsAndXis_outlier "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_lInftyCV_test_tijsAndXis_outlier.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_lInftyCV_test_tijsAndXis_outlier "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_lInftyCV_test_tijsAndXis_outlier.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_lInftyCV_test_tijsAndXis_outlier "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_lInftyCV_test_tijsAndXis_outlier.exe")
else()
  add_test(openMVG_lInftyCV_test_tijsAndXis_outlier NOT_AVAILABLE)
endif()
