# CMake generated Testfile for 
# Source directory: D:/workspace_github/openMVG/src/openMVG/robust_estimation
# Build directory: D:/workspace_github/openMVG/bin64/openMVG/robust_estimation
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_test_rand_sampling "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_test_rand_sampling.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_test_rand_sampling "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_test_rand_sampling.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_test_rand_sampling "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_test_rand_sampling.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_test_rand_sampling "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_test_rand_sampling.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_test_rand_sampling "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_test_rand_sampling.exe")
else()
  add_test(openMVG_test_rand_sampling NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_test_robust_estimator_lineKernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_test_robust_estimator_lineKernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_test_robust_estimator_lineKernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_test_robust_estimator_lineKernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_test_robust_estimator_lineKernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_test_robust_estimator_lineKernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_test_robust_estimator_lineKernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_test_robust_estimator_lineKernel.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_test_robust_estimator_lineKernel "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_test_robust_estimator_lineKernel.exe")
else()
  add_test(openMVG_test_robust_estimator_lineKernel NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_test_robust_estimator_MaxConsensus "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_test_robust_estimator_MaxConsensus.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_test_robust_estimator_MaxConsensus "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_test_robust_estimator_MaxConsensus.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_test_robust_estimator_MaxConsensus "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_test_robust_estimator_MaxConsensus.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_test_robust_estimator_MaxConsensus "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_test_robust_estimator_MaxConsensus.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_test_robust_estimator_MaxConsensus "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_test_robust_estimator_MaxConsensus.exe")
else()
  add_test(openMVG_test_robust_estimator_MaxConsensus NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_test_robust_estimator_Ransac "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_test_robust_estimator_Ransac.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_test_robust_estimator_Ransac "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_test_robust_estimator_Ransac.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_test_robust_estimator_Ransac "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_test_robust_estimator_Ransac.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_test_robust_estimator_Ransac "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_test_robust_estimator_Ransac.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_test_robust_estimator_Ransac "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_test_robust_estimator_Ransac.exe")
else()
  add_test(openMVG_test_robust_estimator_Ransac NOT_AVAILABLE)
endif()
if("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(openMVG_test_robust_estimator_ACRansac "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Debug/openMVG_test_robust_estimator_ACRansac.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(openMVG_test_robust_estimator_ACRansac "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Release/openMVG_test_robust_estimator_ACRansac.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(openMVG_test_robust_estimator_ACRansac "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/MinSizeRel/openMVG_test_robust_estimator_ACRansac.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(openMVG_test_robust_estimator_ACRansac "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/RelWithDebInfo/openMVG_test_robust_estimator_ACRansac.exe")
elseif("${CTEST_CONFIGURATION_TYPE}" MATCHES "^([Mm][Aa][Ii][Nn][Tt][Aa][Ii][Nn][Ee][Rr])$")
  add_test(openMVG_test_robust_estimator_ACRansac "D:/workspace_github/openMVG/bin64/Windows-AMD64-Release/Maintainer/openMVG_test_robust_estimator_ACRansac.exe")
else()
  add_test(openMVG_test_robust_estimator_ACRansac NOT_AVAILABLE)
endif()
